### ISSUE TITLE
Statistical Profiles 

### ISSUE THREAD

**Issue by pressel** [pressel/pycles#3]
I am working on adding IO of statistical profiles.

**Comment by pressel** [comment]
If anyone would like a particular statistic added to the output files please let me know.

**Comment by cmkaul** [comment]
Also, I am working on a module called "AuxiliaryStatistics." This is a place to put case-specific (or cloud-category-specific) output. For example, the first class I have added (in a rough, but working, version) is "CumulusStatistics" to compute the cloud and cloud core conditional statistics reported in the Bomex intercomparison.
